export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',

    SIGNUP_REQUEST: 'SIGNUP_REQUEST',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',

    UPDATE_REQUEST: 'UPDATE_REQUEST',
    UPDATE_FAILURE: 'UPDATE_FAILURE',
    UPDATE_SUCCESS: 'UPDATE_SUCCESS',

    GET_REQUEST: 'GET_REQUEST',
    GET_FAILURE: 'GET_FAILURE',
    GET_SUCCESS: 'GET_SUCCESS',

    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',

    UPDATE_AVATAR_REQUEST: 'UPDATE_AVATAR_REQUEST',
    UPDATE_AVATAR_FAILURE: 'UPDATE_AVATAR_FAILURE',
    UPDATE_AVATAR_SUCCESS: 'UPDATE_AVATAR_SUCCESS',

    UPDATE_COVER_REQUEST: 'UPDATE_COVER_REQUEST',
    UPDATE_COVER_FAILURE: 'UPDATE_COVER_FAILURE',
    UPDATE_COVER_SUCCESS: 'UPDATE_COVER_SUCCESS',

    UPDATE_SERVICE_REQUEST: 'UPDATE_SERVICE_REQUEST',
    UPDATE_SERVICE_FAILURE: 'UPDATE_SERVICE_FAILURE',
    UPDATE_SERVICE_SUCCESS: 'UPDATE_SERVICE_SUCCESS',
}

export const transactionPaymentConstants = {
    CREATE_WITHDRAWAL_REQUEST: 'CREATE_WITHDRAWAL_REQUEST',
    CREATE_WITHDRAWAL_SUCCESS: 'CREATE_WITHDRAWAL_SUCCESS',
    CREATE_WITHDRAWAL_FAILURE: 'CREATE_WITHDRAWAL_FAILURE',

    GET_WITHDRAWAL_REQUEST: 'GET_WITHDRAWAL_REQUEST',
    GET_WITHDRAWAL_SUCCESS: 'GET_WITHDRAWAL_SUCCESS',
    GET_WITHDRAWAL_FAILURE: 'GET_WITHDRAWAL_FAILURE',

    GET_USER_WITHDRAWALS_REQUEST: 'GET_USER_WITHDRAWALS_REQUEST',
    GET_USER_WITHDRAWALS_SUCCESS: 'GET_USER_WITHDRAWALS_SUCCESS',
    GET_USER_WITHDRAWALS_FAILURE: 'GET_USER_WITHDRAWALS_FAILURE',

    APPROVE_WITHDRAWAL_REQUEST: 'APPROVE_WITHDRAWAL_REQUEST',
    APPROVE_WITHDRAWAL_SUCCESS: 'APPROVE_WITHDRAWAL_SUCCESS',
    APPROVE_WITHDRAWAL_FAILURE: 'APPROVE_WITHDRAWAL_FAILURE',

    REJECT_WITHDRAWAL_REQUEST: 'REJECT_WITHDRAWAL_REQUEST',
    REJECT_WITHDRAWAL_SUCCESS: 'REJECT_WITHDRAWAL_SUCCESS',
    REJECT_WITHDRAWAL_FAILURE: 'REJECT_WITHDRAWAL_FAILURE',

    VERIFY_WITHDRAWAL_OTP_REQUEST: "VERIFY_WITHDRAWAL_OTP_REQUEST",
    VERIFY_WITHDRAWAL_OTP_SUCCESS: "VERIFY_WITHDRAWAL_OTP_SUCCESS",
    VERIFY_WITHDRAWAL_OTP_FAILURE: "VERIFY_WITHDRAWAL_OTP_FAILURE"
};

export const ticketTypeConstants = {
    CREATE_TICKET_TYPE_REQUEST: 'CREATE_TICKET_TYPE_REQUEST',
    CREATE_TICKET_TYPE_FAILURE: 'CREATE_TICKET_TYPE_FAILURE',
    CREATE_TICKET_TYPE_SUCCESS: 'CREATE_TICKET_TYPE_SUCCESS',

    UPDATE_REQUEST: 'UPDATE_REQUEST',
    UPDATE_FAILURE: 'UPDATE_FAILURE',
    UPDATE_SUCCESS: 'UPDATE_SUCCESS',

    GET_REQUEST: 'GET_REQUEST',
    GET_FAILURE: 'GET_FAILURE',
    GET_SUCCESS: 'GET_SUCCESS',
}

export const eventReviewConstants = {
    CREATE_REQUEST: 'CREATE_REQUEST',
    CREATE_FAILURE: 'CREATE_FAILURE',
    CREATE_SUCCESS: 'CREATE_SUCCESS',
}

export const searchSelectProviderConstants = {
    GET_REQUEST: 'GET_REQUEST',
    GET_FAILURE: 'GET_FAILURE',
    GET_SUCCESS: 'GET_SUCCESS',

    GET_CATEGORY_REQUEST: 'GET_CATEGORY_REQUEST',
    GET_CATEGORY_FAILURE: 'GET_CATEGORY_FAILURE',
    GET_CATEGORY_SUCCESS: 'GET_CATEGORY_SUCCESS',
}

export const homeAndRecomConstants = {
    GET_REQUEST: 'GET_REQUEST',
    GET_FAILURE: 'GET_FAILURE',
    GET_SUCCESS: 'GET_SUCCESS',
}

export const chatConstants = {
    POST_REQUEST: 'POST_REQUEST',
    POST_SUCCESS: 'POST_SUCCESS',
    POST_FAILURE: 'POST_FAILURE',

    GET_REQUEST: 'GET_REQUEST',
    GET_SUCCESS: 'GET_SUCCESS',
    GET_FAILURE: 'GET_FAILURE',
};

export const activityConstants = {
    FETCH_ACTIVITIES_REQUEST: 'FETCH_ACTIVITIES_REQUEST',
    FETCH_ACTIVITIES_SUCCESS: 'FETCH_ACTIVITIES_SUCCESS',
    FETCH_ACTIVITIES_FAILURE: 'FETCH_ACTIVITIES_FAILURE',
};

export const serviceRequestConstants = {
    ORGANIZER_SERVICE_TO_PROVIDER_REQUEST: 'ORGANIZER_SERVICE_TO_PROVIDER_REQUEST',
    ORGANIZER_SERVICE_TO_PROVIDER_FAILURE: 'ORGANIZER_SERVICE_TO_PROVIDER_FAILURE',
    ORGANIZER_SERVICE_TO_PROVIDER_SUCCESS: 'ORGANIZER_SERVICE_TO_PROVIDER_SUCCESS',

    GET_REQUESTED_SERVICE_REQUEST: 'GET_REQUESTED_SERVICE_REQUEST',
    GET_REQUESTED_SERVICE_FAILURE: 'GET_REQUESTED_SERVICE_FAILURE',
    GET_REQUESTED_SERVICE_SUCCESS: 'GET_REQUESTED_SERVICE_SUCCESS',
}

export const promotionConstants = {
    CREATE_REQUEST: 'CREATE_REQUEST',
    CREATE_FAILURE: 'CREATE_FAILURE',
    CREATE_SUCCESS: 'CREATE_SUCCESS',

    UPDATE_REQUEST: 'UPDATE_REQUEST',
    UPDATE_FAILURE: 'UPDATE_FAILURE',
    UPDATE_SUCCESS: 'UPDATE_SUCCESS',

    GET_REQUEST: 'GET_REQUEST',
    GET_FAILURE: 'GET_FAILURE',
    GET_SUCCESS: 'GET_SUCCESS',
}

export const eventOrderConstants = {
    CREATE_REQUEST: 'CREATE_REQUEST',
    CREATE_FAILURE: 'CREATE_FAILURE',
    CREATE_SUCCESS: 'CREATE_SUCCESS',

    PDF_DOWNLOAD_REQUEST: 'PDF_DOWNLOAD_REQUEST',
    PDF_DOWNLOAD_FAILURE: 'PDF_DOWNLOAD_FAILURE',
    PDF_DOWNLOAD_SUCCESS: 'PDF_DOWNLOAD_SUCCESS',

    GET_REQUEST: 'GET_REQUEST',
    GET_FAILURE: 'GET_FAILURE',
    GET_SUCCESS: 'GET_SUCCESS',

    ENTER_USER_EVENT_REQUEST: 'ENTER_USER_EVENT_REQUEST',
    ENTER_USER_EVENT_FAILURE: 'ENTER_USER_EVENT_FAILURE',
    ENTER_USER_EVENT_SUCCESS: 'ENTER_USER_EVENT_SUCCESS',

    VERIFY_TICKET_REQUEST: 'VERIFY_TICKET_REQUEST',
    VERIFY_TICKET_SUCCESS: 'VERIFY_TICKET_SUCCESS',
    VERIFY_TICKET_FAILURE: 'VERIFY_TICKET_FAILURE',
}

export const eventConstants = {
    GET_TODAY_EVENT_REQUEST: "GET_TODAY_EVENT_REQUEST",
    GET_TODAY_EVENT_SUCCESS: "GET_TODAY_EVENT_SUCCESS",
    GET_TODAY_EVENT_FAILURE: "GET_TODAY_EVENT_FAILURE",

    EVENT_CATEGORY_FETCH_REQUEST: "EVENT_CATEGORY_FETCH_REQUEST",
    EVENT_CATEGORY_FETCH_SUCCESS: "EVENT_CATEGORY_FETCH_SUCCESS",
    EVENT_CATEGORY_FETCH_FAILURE: "EVENT_CATEGORY_FETCH_FAILURE",

    SINGLE_CATEGORY_FETCH_REQUEST: "SINGLE_CATEGORY_FETCH_REQUEST",
    SINGLE_CATEGORY_FETCH_SUCCESS: "SINGLE_CATEGORY_FETCH_SUCCESS",
    SINGLE_CATEGORY_FETCH_FAILURE: "SINGLE_CATEGORY_FETCH_FAILURE",

    CHILD_CATEGORY_FETCH_REQUEST: "CHILD_CATEGORY_FETCH_REQUEST",
    CHILD_CATEGORY_FETCH_SUCCESS: "CHILD_CATEGORY_FETCH_SUCCESS",
    CHILD_CATEGORY_FETCH_FAILURE: "CHILD_CATEGORY_FETCH_FAILURE",

    EVENT_BY_ID_REQUEST: 'EVENT_BY_ID_REQUEST',
    EVENT_BY_ID_FAILURE: 'EVENT_BY_ID_FAILURE',
    EVENT_BY_ID_SUCCESS: 'EVENT_BY_ID_SUCCESS',

    EVENT_SUBMIT_RATING_REQUEST: 'EVENT_SUBMIT_RATING_REQUEST',
    EVENT_SUBMIT_RATING_FAILURE: 'EVENT_SUBMIT_RATING_FAILURE',
    EVENT_SUBMIT_RATING_SUCCESS: 'EVENT_SUBMIT_RATING_SUCCESS',

    EVENT_GET_RATING_REQUEST: 'EVENT_GET_RATING_REQUEST',
    EVENT_GET_RATING_FAILURE: 'EVENT_GET_RATING_FAILURE',
    EVENT_GET_RATING_SUCCESS: 'EVENT_GET_RATING_SUCCESS',

    WISHLIST_ADD_REQUEST: 'WISHLIST_ADD_REQUEST',
    WISHLIST_ADD_FAILURE: 'WISHLIST_ADD_FAILURE',
    WISHLIST_ADD_SUCCESS: 'WISHLIST_ADD_SUCCESS',

    WISHLIST_GET_REQUEST: 'WISHLIST_GET_REQUEST',
    WISHLIST_GET_FAILURE: 'WISHLIST_GET_FAILURE',
    WISHLIST_GET_SUCCESS: 'WISHLIST_GET_SUCCESS',

    EVENT_CREATE_REQUEST: 'EVENT_CREATE_REQUEST',
    EVENT_CREATE_FAILURE: 'EVENT_CREATE_FAILURE',
    EVENT_CREATE_SUCCESS: 'EVENT_CREATE_SUCCESS',

    EVENT_GET_REQUEST: 'EVENT_GET_REQUEST',
    EVENT_GET_FAILURE: 'EVENT_GET_FAILURE',
    EVENT_GET_SUCCESS: 'EVENT_GET_SUCCESS',

    EVENT_UPDATE_REQUEST: 'EVENT_UPDATE_REQUEST',
    EVENT_UPDATE_FAILURE: 'EVENT_UPDATE_FAILURE',
    EVENT_UPDATE_SUCCESS: 'EVENT_UPDATE_SUCCESS',

    EVENT_CUSTOMIZATION_UPDATE_REQUEST: 'EVENT_CUSTOMIZATION_UPDATE_REQUEST',
    EVENT_CUSTOMIZATION_UPDATE_FAILURE: 'EVENT_CUSTOMIZATION_UPDATE_FAILURE',
    EVENT_CUSTOMIZATION_UPDATE_SUCCESS: 'EVENT_CUSTOMIZATION_UPDATE_SUCCESS',

    PUBLISH_CREATE_REQUEST: 'PUBLISH_CREATE_REQUEST',
    PUBLISH_CREATE_FAILURE: 'PUBLISH_CREATE_FAILURE',
    PUBLISH_CREATE_SUCCESS: 'PUBLISH_CREATE_SUCCESS',

    TICKET_CONFIG_CREATE_REQUEST: 'TICKET_CONFIG_CREATE_REQUEST',
    TICKET_CONFIG_CREATE_FAILURE: 'TICKET_CONFIG_CREATE_FAILURE',
    TICKET_CONFIG_CREATE_SUCCESS: 'TICKET_CONFIG_CREATE_SUCCESS',

    EVENT_CUSTOMIZTION_CREATE_REQUEST: 'EVENT_CUSTOMIZTION_CREATE_REQUEST',
    EVENT_CUSTOMIZTION_CREATE_FAILURE: 'EVENT_CUSTOMIZTION_CREATE_FAILURE',
    EVENT_CUSTOMIZTION_CREATE_SUCCESS: 'EVENT_CUSTOMIZTION_CREATE_SUCCESS',
}

export const serviceReqConstants = {
    CREATE_REQUEST: 'CREATE_REQUEST',
    CREATE_FAILURE: 'CREATE_FAILURE',
    CREATE_SUCCESS: 'CREATE_SUCCESS',
}

export const userPersonalServiceReqConstants = {
    CREATE_REQUEST: 'CREATE_REQUEST',
    CREATE_FAILURE: 'CREATE_FAILURE',
    CREATE_SUCCESS: 'CREATE_SUCCESS',
}

export const reminderConstants = {
    SAVE_REQUEST: 'REMINDER_SETTINGS_SAVE_REQUEST',
    SAVE_SUCCESS: 'REMINDER_SETTINGS_SAVE_SUCCESS',
    SAVE_FAILURE: 'REMINDER_SETTINGS_SAVE_FAILURE',
};