export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',

    SIGNUP_REQUEST: 'SIGNUP_REQUEST',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',

    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
}

export const ticketTypeConstants = {
    CREATE_TICKET_TYPE_REQUEST: 'CREATE_TICKET_TYPE_REQUEST',
    CREATE_TICKET_TYPE_FAILURE: 'CREATE_TICKET_TYPE_FAILURE',
    CREATE_TICKET_TYPE_SUCCESS: 'CREATE_TICKET_TYPE_SUCCESS',
}